server:
  port: 8082
spring:
  application:
    name: ms2-swagger-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
springdoc:
  swagger-ui:
    oauth:
      clientId: client1
      clientSecret: secret
      usePkceWithAuthorizationCodeGrant: false