aggregator.eureka.enabled: true

swagger-params:
  issuerUri: ${params.oauth2.issuerUri}
  servers:
    liste:
      - uri: http://localhost:${server.port}
        description: Local environment
      - uri: http://10.0.0.137:${server.port}
        description: Development environment
      - uri: http://10.0.0.500:${server.port}
        description: Homologation environment
      - uri: http://10.0.0.500:${server.port}
        description: Production environment
  aggregator:
    enabled: ${aggregator.eureka.enabled:false}
    cors:
      uri: ${params.swaggerAggregator.uri}
###################################################################
#dev
params:
  eureka:
    uri: http://container-gr-eureka-server:8761/eureka/
  oauth2:
    issuerUri: http://container-gr-auth-server:8764
  gatewayOauth2:
    uri: http://GR-API-GATEWAY
  swaggerAggregator:
    uri: http://container-gr-conf-aggregator-server:8765
  zipkin:
    uri: http://container-zipkin:9411
  keystore:
    type: PKCS12
    path: file:/certificates/ms2.p12
    password: jihed123
    alias: ms2
  truststore:
    path: /certificates/ms1-truststore.jks
    password: jihed1234
###################################################################
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    # Activer le mode "try it out" pour tous les endpoints
    try-it-out-enabled: true
    oauth:
      clientId: gr-oauth2-swagger-ms1
      clientSecret: swagger-ms1
  show-actuator: false # activer sinon pour voir les endpoints actuator dans le swagger.
###################################################################
caller:
  destination:
    # gr-oauth2-swagger-ms1 from swagger.
    client0:
      resourceUri:
      clientId: gr-oauth2-swagger-ms1
      clientSecret: swagger-ms1
      scopes: read,write
      registrationId: gr-oauth2-swagger-ms1