aggregator.eureka.enabled: true
params.restTemplateConfiguration.enabled: false
swagger-params.enabled: true

swagger-params:
  issuerUri: ${params.oauth2.issuerUri}
  servers:
    liste:
      - uri: http://localhost:${server.port}
        description: Local environment
      - uri: http://10.0.0.137:${server.port}
        description: Development environment
      - uri: http://10.0.0.500:${server.port}
        description: Homologation environment
      - uri: http://10.0.0.500:${server.port}
        description: Production environment
  aggregator:
    enabled: ${aggregator.eureka.enabled:false}
    cors:
      uri: ${params.swaggerAggregator.uri}
###################################################################
#local
params:
  eureka:
    uri: http://localhost:8761/eureka/
  oauth2:
    issuerUri: http://localhost:8764
  gatewayOauth2:
    uri: http://SPRINGBOOT-CONF-GATEWAY-API-OAUTH2
  swaggerAggregator:
    uri: http://localhost:8765
  zipkin:
    uri: http://localhost:9411
  keystore:
    type: PKCS12
    path: file:C:/E/TOOLS/ms2.p12
    password: jihed123
    alias: ms2
  truststore:
    path: C:/E/TOOLS/ms1-truststore.jks
    password: jihed1234
###################################################################
springdoc:
  swagger-ui:
    oauth:
      clientId: gr-oauth2-swagger-ms1
      clientSecret: swagger-ms1
###################################################################
caller:
  destination:
    # gr-oauth2-swagger-ms1 from swagger.
    client0:
      resourceUri:
      clientId: gr-oauth2-swagger-ms1
      clientSecret: swagger-ms1
      scopes: read,write
      registrationId: gr-oauth2-swagger-ms1